version: '3'
services:
  keycloak:
    image: keycloak/keycloak:18.0.0
    environment: 
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
    command:
      - start-dev --hostname-admin-url=https://moodgiver.ga
    ports:
      - 8080:8080
    networks: 
      - keycloak-demo
  nginx: 
    build: 
      context: ./nginx
    ports: 
      - 80:80
    networks: 
      - keycloak-demo

networks: 
  keycloak-demo: {}