version: '3'
services:
  keycloak:
    image: keycloak/keycloak:18.0.0
    environment: 
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
      - QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH=8192
    command:
      - start-dev
    ports:
      - 80:8080
    # networks: 
    #   - keycloak-demo
  # nginx: 
  #   build: 
  #     context: ./nginx
  #   ports: 
  #     - 80:80
  #   networks: 
  #     - keycloak-demo

# networks: 
#   keycloak-demo: {}