version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment: 
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
      - QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH=8192
    command:
      - start-dev
    ports:
      - 8080:8080
    networks: 
      - keycloak-demo
  nginx: 
    build: 
      context: ./nginx
    ports: 
      - 80:80
    networks: 
      - keycloak-demo

networks: 
  keycloak-demo: {}